version: "2.1"

services:

  zookeeper:
    image: zookeeper:3.5.6
    restart: always
    hostname: zoo
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 #todo from environment
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
